@hostname = http://127.0.0.1:5000/api/v1/user-staffs
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiJ2c2tkNzd0eCIsInVzZXJfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTcxNTU4MDk0M30.OVIrHvw1RJzPv7M5C88B7PbspaPKWh49wOZIqC86so4

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "user1",
    "email": "user1@gmail.com",
    "phone_number": "01779876546",
    "parmenent_address": "khulna, jessore",
    "present_address": "dhaka, mirpur",
    "image": "/assets/dashboard/images/avatar.png",
    "password": "$2a$12$.aO5lxRR2qnICFEhMGaK8.aoAut89QnkhMn4hASjuvXfDA9StWAp6"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json
Authorization: {{token}}

{
    "id": 4,
    "name": "Hasib",
    "email": "hasib@gamil.com",
    "phone_number": "01779876546",
    "image": "/assets/dashboard/images/avatar.png"
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    # "id": 4
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    # "id": 6
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 6
}