@hostname = http://127.0.0.1:5000/api/v1/user-branch-admins
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiJ2c2tkNzd0eCIsInVzZXJfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTcxNTU4MDk0M30.OVIrHvw1RJzPv7M5C88B7PbspaPKWh49wOZIqC86so4

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/2 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "Tamim",
    "email": "tamim@gamil.com",
    "phone_number": "01779876546",
    "image": "/assets/dashboard/images/avatar.png",
    "status": "active",
    "password": "1234"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json
Authorization: {{token}}

{
    "id": 2,
    "name": "Hamim",
    "email": "hamim@gamil.com",
    "phone_number": "01779876546",
    "image": "/assets/dashboard/images/avatar.png",
    "status": "active",
    "password": "1234"
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    # "id": 2
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 2
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 5
}