@hostname = http://127.0.0.1:5000/api/v1/user-login-history
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiIzYXIyczFjZCIsInVzZXJfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTcxNTQxODkzOH0.fp9Ar3jaNvQLo7C0lwV2JqtAILulCWUwNcSnBZfg2SY

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "user_id": 1,
    "user_table_name": "user_staffs",
    "date": "12:12:2024",
    "device": "phone"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json
Authorization: {{token}}

{
    "id": 4,
    "name": "Habib",
    "email": "habib@gamil.com",
    "phone_number": "01779876546",
    "image": "/assets/dashboard/images/avatar.png"
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    # "id": 4
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 4,
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 3
}