@hostname = http://127.0.0.1:5000/api/v1/auth

# login
###
POST {{hostname}}/login HTTP/1.1
content-type: application/json

{
    "email": "user1@gmail.com",
    "password": "12345678"
}

# auth user
###
GET {{hostname}}/info HTTP/1.1
content-type: application/json
# Cookie: key = value

# forget mail
###
POST {{hostname}}/forget HTTP/1.1
content-type: application/json

{}

# logout
###
POST {{hostname}}/logout HTTP/1.1
content-type: application/json

{}