@hostname = http://127.0.0.1:5000/api/v1/admin-users

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10   HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "name": "user4",
    "email": "user4@gmail.com",
    "phone_number": "35897593784",
    "image": "avatar.png",
    "password": "1234"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
     "id": 5,
     "name": "user5update",
    "email": "user5update@gmail.com",
    "phone_number": "35897593784",
    "image": "avatar.png"
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 2
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 3
}

# block
###
POST  {{hostname}}/block HTTP/1.1
content-type: application/json

{
    "id": 3
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 2
}